name: Build and Deploy

on:
  push:
    branches: [ master, hr ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run deploy
        run: bash build.sh
