export interface Saf2024EventDetail {
  contactInfo?: string[];
  images?: Array<{ src: string; alt: string }>;
  registerHref?: string;
  sections?: Array<{ title: string; lines: string[] }>;
}

interface Saf2024RawDetail {
  contactInfo?: string[];
  lines: string[];
  registerHref?: string;
}

const normalizeSectionTitle = (line: string) => {
  const clean = line.replace(/^I\s+/, '').trim();
  const titleMap: Record<string, string> = {
    Overview: 'Overview',
    'Event Description': 'Event Description',
    Program: 'Program',
    'Program / Program': 'Program',
    Speakers: 'Speakers',
    'Contact Point': 'Contact Point',
    Registration: 'Registration',
    'Registration Link': 'Registration',
  };
  return titleMap[clean];
};

const buildSections = (lines: string[]) => {
  const sections: Array<{ title: string; lines: string[] }> = [];
  let current: { title: string; lines: string[] } = { title: 'Overview', lines: [] };

  const pushCurrent = () => {
    const cleanedLines = current.lines.map((line) => line.trim()).filter(Boolean);
    if (cleanedLines.length === 0) return;
    sections.push({ title: current.title, lines: cleanedLines });
  };

  lines.forEach((line) => {
    const title = normalizeSectionTitle(line);
    if (title) {
      const isInitialDuplicateOverview = title === 'Overview'
        && current.title === 'Overview'
        && current.lines.length <= 1
        && sections.length === 0;

      if (!isInitialDuplicateOverview) {
        pushCurrent();
      }
      current = { title, lines: [] };
      return;
    }
    if (line === '< Back') return;
    current.lines.push(line);
  });

  pushCurrent();
  return sections;
};

const saf2024RawDetails: Record<string, Saf2024RawDetail> = {
  "복제-mon-yoon-yang": {
    contactInfo: ["skim@secretariat-intl.com"],
    registerHref: "https://docs.google.com/forms/d/1A6BVNK6LziwA31LUf0eyJ-W3Sj_0IInhz9tWIfY034w/viewform?edit_requested=true",
    lines: [
      "Commercial, cultural and legal challenges in cross-border construction projects",
      "I Overview",
      "Date: Monday, 28 October 2024",
      "Time: 09:00 - 11:30",
      "Format: In-person",
      "Language: English",
      "Venue: KCAB Hearing Room 1, 18F Trade Tower, 511 Yeongdong-daero, Gangnam District, Seoul, South Korea",
      "Hosts:​​​",
      "I Event Description",
      "What type of the commercial, cultural and legal challenges have you experienced when dealing with cross-border construction projects? Such challenges tend to become more complex in international projects where key players (for example, employer, contractor, sub-contractor, supplier, PMC/CMC and their staff) come from different regions and background. Each of these project participants may have different perception as to what should be regarded as the best practices at different stages of projects.",
      "Our esteemed panelists will discuss their experience in dealing with such challenges at front end of projects (Session 1) and when disputes arise (Session 2), and ways to resolve them.",
      "I Program",
      "9am Coffee / Breakfast networking",
      "9.30 am to 11.30 am Seminar",
      "Session 1: Challenges at front end of projects",
      "Session 2: Challenges when disputes arise",
      "I Speakers",
      "Welcome Address:",
      "Steve Kim, Secretary-General, KCAB INTERNATIONAL",
      "KJ Park, SCL Korea/ Partner, Yulchon",
      "Moderator:",
      "Sue Kim, SCL Korea/ Director, Secretariat",
      "Session 1 Speakers",
      "Joseph Lee, SCL Korea/ Partner, Yoon & Yang LLC",
      "Tony Dymond, Partner, Debevoise & Plimpton LLP",
      "Woojae Kim, Partner, BAE, KIM & LEE LLC",
      "Sara Paradisi, Partner, Rosenblatt",
      "Mike Allen, Managing Director, Secretariat",
      "Session 2 Speakers",
      "Sangchul Kim, SCL Korea /Partner, BAE, KIM & LEE LLC",
      "Sangyub (Sean) Lee, Deputy Director, KCAB INTERNATIONAL",
      "Peter Turner KC, Solicitor & avocat à la Cour (France), 39 Essex Chambers",
      "Kaiser Leung, Barrister, Des Voeux Chambers",
      "Ji Yoon Park, Counsel, Chief Representative of the Seoul office of HKIAC",
      "I Contact Point",
      "​ Name: Sue Kim / Email: skim@secretariat-intl.com",
    ],
  },
  "mon-yulchoon-yendallhunter": {
    contactInfo: ["s_imyoo@yulchon.com"],
    registerHref: "https://www.yulchon.com/en/seminars/seminars-view/602/page.do",
    lines: [
      "Delay and Delay Damage Claims in Construction Projects",
      "I Overview",
      "Date: Monday, October 28, 2024",
      "Time: 11:00 A.M to 13:00 P.M",
      "Format: In-person",
      "Language: English",
      "Venue: Yulchon Lecture Hall (Parnas Tower, 39F, 521 Teheran-ro, Gangnam-gu, Seoul 06164, Korea)",
      "Hosts:​​​",
      "I Event Description",
      "This seminar will provide exclusive insights into managing delays and addressing delay damage claims-critical issues for the success of construction projects. Renowned professionals, including experienced lawyers, technical experts, and an arbitrator, will be sharing their knowledge and firsthand experience on how to successfully pursue and defend delay claims.",
      "Key topics to be discussed:",
      "​",
      "•The legal frameworks governing delay and delay damages claims.",
      "•Proven strategies for effectively managing and mitigating delay risks.",
      "•Essential documentation and submission practices for delay claims.",
      "•Case studies highlighting best practices in arbitration and legal resolution of delay disputes.",
      "This is a unique opportunity to learn directly from industry-leading professionals who have extensive experience navigating complex delay claims and achieving favorable outcomes.",
      "Whether you are a project manager, contractor, legal consultant, or an engineer, this seminar will provide you with practical knowledge and actionable strategies that you can apply to protect your projects from delays and ensure fair compensation.",
      "I Program",
      "TBD",
      "I Speakers",
      "Lee Kyung Jun, Kang Hyun Gyu (Yulchon)",
      "Emily Simnor, JB Kim (Yendall Hunter)",
      "Andrew Rigney (Crown Office Chambers)",
      "I Contact Point",
      "​ Name: Yoo Ji Min / Email: s_imyoo@yulchon.com",
    ],
  },
  "복제-tue-dis": {
    contactInfo: ["jlee@yoonyang.com"],
    registerHref: "https://forms.gle/myT4K9erhiugxz6g7",
    lines: [
      "New and Renewable Energy Landscape in Korea and Beyond – Current Issues in Project Development and Dispute Resolution",
      "I Overview",
      "Date: Monday, 28 October 2024",
      "Time: 12:30 – 14:30 (Registration starts at 12:00 with sandwich and refreshments)",
      "Format: In-person",
      "Language: Korean / English",
      "Venue: Hearing Room 1 at KCAB International",
      "Hosts:​​​",
      "I Event Description",
      "Our seminar “New and Renewable Energy Landscape in Korea and Beyond – Current Issues in Project Development and Dispute Resolution” will comprise two sessions – first session covering current issues in energy project development in Korea and second session covering dispute resolution trends in Korea and other jurisdiction such as Southeast Asia and Middle East.",
      "​",
      "In the first session, the speakers from Yoon & Yang’s New and Renewable Energy Practice Group will discuss the current issues in the energy landscape in Korea for project development such as energy supply, grid and network connection in Korea. In this session, the speakers will also share their experience in resolving the difficulties project developers face in Korea.",
      "In the second session, the speakers from Yoon & Yang, 39 Essex Chamber and Al Tamimi will share their experience on dispute resolution in respect of new and renewable projects in locations such as Korea, Southeast Asia and Middle East.",
      "I Program",
      "Session 1 (12:30 – 13:30): Current Issues in New and Renewable Energy Project Development in Korea",
      "Speakers Joon Oh Jo / Dae Sagong / David Lee",
      "Session 2 (13:30 – 14:30): Dispute Resolution Trends in New and Renewable Project",
      "Speakers Steven Lim / Paul Taylor / Joseph Lee",
      "I Speakers",
      "Joon Oh Jo / Yoon & Yang / Partner",
      "Dae Sagong / Yoon & Yang / Partner",
      "David Lee / Yoon & Yang / Senior Foreign Attorney",
      "Joseph Lee / Yoon & Yang / Senior Foreign Attorney",
      "Steven Lim / 39 Essex Chambers / Arbitrator & Barrister",
      "Paul Taylor / Al Tamimi & Company / Partner",
      "Introduction by Myung-Ahn Kim / Yoon & Yang / Senior Foreign Attorney",
      "I Contact Point",
      "​ Name: Joseph Lee / Email: jlee@yoonyang.com",
    ],
  },
  "mon-jusmundi-yulchon": {
    contactInfo: ["j.petrila@jusmundi.com"],
    registerHref: "https://talkbase.io/event/shaping-the-future-of-arbitration-and-international-law/jus-mundi",
    lines: [
      "Innovating Justice: How Tech is Shaping the Future of Arbitration & International Law",
      "I Overview",
      "Date: Monday, 28 October 2024",
      "Time: 15:00 - 17:00",
      "Format: In-person",
      "Language: English",
      "Objective: Provide attendees with a thorough overview of emerging technologies in arbitration, from current implementations to their future implications such as AI",
      "Hosts:",
      "I Event Description",
      "Yulchon LLC and Jus Mundi are delighted to invite participants of this year's ADR Festival to a riveting discussion on how tech is shaping the future of Arbitration and International Law.",
      "Join our esteemed panelists to take a look at how the growing impact of AI and other emerging technologies are impacting the everyday practice of arbitrators and lawyers, covering real-life applications.",
      "I Speakers",
      "David MacArthur, Partner and Co-head of IDR, Yulchon LLC (moderator)",
      "Sae Youn Kim, Partner, Kim & Chang",
      "Saemee Kim, Partner, Lee & Ko",
      "Zac Sharpe, Partner, Jones Day",
      "Alexandre Vagenheim, Vice-President of Global Legal Data, Jus Mundi",
      "I Contact Point",
      "​ Name: Joseph Petrila / Email: j.petrila@jusmundi.com",
    ],
  },
  "mon-kim-chang-debevoise-plimpton": {
    contactInfo: ["arbitration_news@kimchang.com"],
    registerHref: "https://www.kimchang.com/en/rsvp/registration.kc?idx=726&user_yn=accept",
    lines: [
      "Arbitrating Private Equity Disputes",
      "I Overview",
      "Date: Monday, October 28, 2024",
      "Time: 16:00 – 17:30 (Registration: 15:30 -)",
      "Format: In-person",
      "Language: English",
      "Venue: KCAB Hearing Room No. 5",
      "Hosts:​​​",
      "I Event Description",
      "What are the risks and opportunities for private equity stakeholders in resolving disputes through international arbitration? How can investors best position themselves to assert and enforce their rights effectively and efficiently? In this seminar, jointly hosted by Kim & Chang and Debevoise & Plimpton, the panel will explore:",
      "Claims against states under investment treaties",
      "Disputes between general partners, limited partners, managers and co-investors",
      "Disputes relating to the acquisition and disposal of investments",
      "Please join us in this conversation during the Seoul ADR Festival 2024.",
      "I Program",
      "15:30 – 16:00 Registration",
      "16:00 – 16:05 Introduction",
      "16:05 – 17:20 Seminar",
      "17:20 – 17:30 Q&A",
      "I Speakers",
      "Tony Dymond, Partner, Debevoise & Plimpton LLP",
      "Jeffrey Sullivan KC, Partner, Debevoise & Plimpton LLP",
      "Cameron Sim, International Counsel, Debevoise & Plimpton LLP",
      "Byung-Chol (B.C.) Yoon, Attorney, Kim & Chang",
      "Chul-Won Lee, Attorney, Kim & Chang",
      "Sup-Joon Byun, Foreign Attorney, Kim & Chang",
      "Boram Hong, Attorney, Kim & Chang",
      "I Contact Point",
      "​ Email: arbitration_news@kimchang.com",
    ],
  },
  "hka-lee-ko-yulchonandcliffordchance": {
    contactInfo: ["asiapacific@hka.com"],
    registerHref: "https://content.hka.com/seoul-adr-festival-side-event-28-october-2024",
    lines: [
      "Beyond the courtroom: Insider strategies to tip the scales in your favour",
      "I Overview",
      "Date: Monday, 28 October 2024",
      "Time: 16:00 - 18:30",
      "Format: In-person",
      "Language: English",
      "Venue: KCAB, Hearing Room 1",
      "Hosts:​​​",
      "I Event Description",
      "Arbitration plays a crucial role in the legal landscape, offering an alternative method of dispute resolution. It handles a variety of matters and operates under less formal procedures than court hearings, often resulting in more expedient case resolutions.",
      "Join HKA, Yulchon, Lee & Ko, Clifford Chance and Al Tamimi & Co for a panel discussion featuring a distinguished line-up of dispute resolution experts who will delve into the practices and nuances of arbitration proceedings.",
      "Attendees will gain valuable insights into:",
      "The power of pre-dispute planning",
      "Key considerations during the vetting and selection process of the tribunal",
      "Differences between common law and civil law in arbitration",
      "Procedural tactics to gain the upper hand in arbitration",
      "Using expert evidence to your advantage",
      "Moderated by Ms Hyunyang Koo, Partner at Lee & Ko, the panel is made up of Mr Jae Hyong Woo, Partner at Yulchon, Mr Paul Sandosham, Partner at Clifford Chance, Mr Martin Leatham, Principal at HKA and Mr Naief Yahia, Partner at Al Tamimi & Co.",
      "I Program",
      "4:00 pm Registration and networking",
      "4:30 pm Opening remarks",
      "4:40 pm Introduction to the panel",
      "4:50 pm Panel discussion",
      "6:20 pm Closing remarks",
      "6:30 pm Close",
      "I Speakers",
      "Panel moderator",
      "Hyunyang Koo, Partner, Lee & Ko",
      "Panellists",
      "Jae Hyong Woo, Partner, Yulchon",
      "Paul Sandosham, Partner, Clifford Chance",
      "Martin Leatham, Principal, HKA",
      "Naief Yahia, Partner, Al Tamimi & Co",
      "I Contact Point",
      "​ Name: Crystal Lim / Email: asiapacific@hka.com",
    ],
  },
  "mon-bakermckenzie": {
    contactInfo: ["sunyoung.kim@bakermckenziekorea.com"],
    lines: [
      "Baker McKenzie KL Partners Drinks Reception",
      "I Overview",
      "Date: Monday, 28 October 2024",
      "Time: 20:30 until late night",
      "Format: In-person",
      "Language: English",
      "Venue: Bar Liquid Soul (Address: B1, 46 Seoraero Seochogu, Seoul)",
      "Hosts:​​​",
      "I Program",
      "Drinks reception",
      "I Contact Point",
      "​ Name: Sunyoung Kim / Email: sunyoung.kim@bakermckenziekorea.com",
      "I Registration",
      "This event is by invitation only.",
    ],
  },
  "tue-hka": {
    contactInfo: ["crystallim@hka.com"],
    registerHref: "https://content.hka.com/charity-walk-seoul",
    lines: [
      "HKA Charity Walk and Breakfast",
      "I Overview",
      "Date: Tuesday, October 29, 2024",
      "Time: 07:30 - 09:15",
      "Format: In-person",
      "Language: N/A",
      "Venue: Meet at Grand Intercontinental Seoul Parnas, Teheran-ro, 521 Gangnam District, Seoul, South Korea",
      "Breakfast: 듬북담북 선릉1점 Dotbukdambuk Seolleung 1st branch, 9 Teheran-ro 69-gil, Samseong-dong, Gangnam District, Seoul, South Korea",
      "Hosts:​​​",
      "I Event Description",
      "Join HKA on Tuesday, 29 October for a fundraising walk through Seolleung and Jeongneung Royal Tombs. We will be raising funds for Community Chest of Korea, a local charity that provides support to the underprivileged including the disabled, the elderly, and children.",
      "​",
      "The leisurely walk will begin from the Grand Intercontinental Seoul Parnas at 7:30am and end at Dotbukdambuk Seolleung 1st branch, where we will enjoy a traditional Korean breakfast.",
      "For every person who joins the walk, HKA will donate to the Community Chest of Korea, and each participant will have a tree adopted in their name through Ecomatcher.",
      "I Program",
      "7:30 am Meet at Grand Intercontinental Seoul Parnas",
      "7:35 am Depart Grand Intercontinental Seoul Parnas for a leisurely walk around Seolleung and Jeongneung Royal Tombs.",
      "8:30 am Dotbukdambuk Seolleung 1st branch for breakfast",
      "I Speakers",
      "N/A",
      "I Contact Point",
      "​ Name: Crystal Lim / Email: crystallim@hka.com",
    ],
  },
  "tue-siac-ysiac": {
    contactInfo: ["jayshin@siac.org.sg"],
    registerHref: "https://siac.org.sg/event/siac-ysiac-present-the-art-of-cross-examination-mock-proceedings-and-a-discussion-on-effective-cross-examination",
    lines: [
      "SIAC-YSIAC present The Art of Cross-Examination: Mock Proceedings and a Discussion on Effective Cross-Examination",
      "I Overview",
      "Date: Tuesday, October 29, 2024",
      "Time: 09:00 - 12:00",
      "Language: English",
      "Venue: Peter & Kim #3805 Trade Tower 511 Yeongdong-daero, Gangnam-gu Seoul, 06164 Korea",
      "Hosts:​​​",
      "I Event Description",
      "The workshop features a mock cross-examination of factual witnesses by experienced practitioners and in-house counsel that will showcase their techniques in a mock hearing, followed by a panel discussion on advocacy strategies and tips.",
      "I Contact Point",
      "​ Name: Jay Shin / Email: jayshin@siac.org.sg",
    ],
  },
  "tue-uncitral-ministryofjustice": {
    lines: [
      "2024 KMOJ - UNCITRAL ADR Special Session",
      "(invitation-only)",
      "I Overview",
      "Date: Tuesday, October 29, 2024",
      "Time: 09:30 - 16:30",
      "Format: In-person / Virtual: UNCITRAL RCAP Zoom",
      "Venue: KCAB INTERNATIONAL Hearing Room 1 (18th floor, Trade Tower),",
      "Hosts:​​​",
      "I Event Description",
      "The 2024 KMOJ – UNCITRAL ADR Special Session, an annual flagship event co-hosted by UNCITRAL RCAP and the Ministry of Justice of the Republic of Korea is taking place on 29 October 2024 in Seoul, Republic of Korea.",
      "​",
      "Themed “UNCITRAL and Regional Developments on Dispute Resolution”, this year’s ADR Special Session brings together representatives from Central Asia and other Asia-Pacific jurisdictions to discuss the latest developments in international commercial arbitration and mediation across the region. Deputy Minister of Justice Hong-Sik (Justin) Chung and the Secretary of UNCITRAL Anna Joubin-Bret will deliver co-opening remarks.",
      "I Registration",
      "The event is open to government officials by invitation only.",
    ],
  },
  "tue-kim-chang-kcci": {
    contactInfo: ["arbitration_news@kimchang.com"],
    registerHref: "https://www.kimchang.com/ko/rsvp/viewOnline.kc?idx=724",
    lines: [
      "에너지 전환 시대의 새로운 법적 과제 - 국내 해상풍력 및 해외 에너지 자원 개발의 법적 문제를 중심으로",
      "I Overview",
      "Date: 2024년 10월 29일 (화)",
      "Time: 10:00 ~ 12:00 (세미나), 12:00 ~ 12:30 (리셉션)",
      "Format: In-person",
      "Language: Korean/한국어",
      "Venue: 김·장 법률사무소 크레센도빌딩 3층",
      "Hosts:​​​",
      "I Event Description",
      "N/A",
      "I Program / Program",
      "10:00 ~ 10:05 개회사 김세연 변호사 (김∙장 법률사무소)",
      "10:05 ~ 11:00 Session 1 - 국내 해상풍력 프로젝트 계약, 인허가, 공사수행의 주요 법적 리스크",
      "사회 : 조은아 외국변호사 (김∙장 법률사무소)",
      "발표 : Ryan Russell 외국변호사 (김∙장 법률사무소), 박준환 변호사 (김∙장 법률사무소), 박설 변호사 (김∙장 법률사무소)",
      "토론 : 권지안 상무 (Copenhagen Infrastructure Partners), 박혜민 변호사 (김∙장 법률사무소)",
      "11:00 ~ 11:45 Session 2 - 해외 에너지 자원개발 사업 관련 주요 법적 리스크",
      "사회 : 이철원 변호사 (김∙장 법률사무소)",
      "발표 : 정다운 외국변호사 (김∙장 법률사무소), 김도영 변호사 (김∙장 법률사무소)",
      "토론 : 허준 파트장 (한국광해광업공단), 김성환 변호사 (SK E&S), 노현식 변호사 (김∙장 법률사무소)",
      "11:45 ~ 12:00 Q&A Session / 발표자/토론자 논의 & 질의응답",
      "12:00 ~ 12:30 리셉션",
      "I Contact Point",
      "Email: arbitration_news@kimchang.com",
    ],
  },
  "baekim-lee": {
    contactInfo: ["woojae.kim@bkl.co.kr", "hangil.lee@bkl.co.kr", "bochan.kim@bkl.co.kr"],
    registerHref: "https://forms.gle/KsY3jJqNYp924SXz8",
    lines: [
      "Navigating Enforcement Proceedings: Practical Strategies, Tips, and Pitfalls from Leading Cases",
      "I Overview",
      "Date: Tuesday, October 29, 2024",
      "Time: 10:30 - 12:00",
      "Format: In-person",
      "Language: English",
      "Venue: 25th Floor, BAE, KIM & LEE LLC",
      "Hosts:​​​",
      "I Event Description",
      "During this seminar, BKL attorneys will share their ample experience in enforcing arbitral awards in Korea. As arbitration continues to be a preferred method for resolving disputes in both domestic and international contexts, understanding the nuances of enforcing these awards is critical for legal practitioners, corporate counsel, and other stakeholders. The seminar will aim to illuminate the complexities and unique features concerning the legal frameworks that govern the enforcement of arbitration awards in Korea.",
      "Participants will gain valuable insights into the mechanisms available for enforcing awards, as well as the challenges and best practices associated with these processes. The topics for discussion include the following:",
      "Korean Arbitration Act: A detailed overview of the legal provisions that underpin arbitration in Korea, including their implications for enforcement.",
      "Domestic vs. International Enforcement: A comparative analysis of enforcement procedures for domestic and international arbitration awards, highlighting key differences and considerations.",
      "Judicial Practice: Discussion of recent case law and judicial interpretations that have shaped the enforcement landscape in Korea, including landmark decisions and emerging trends.",
      "Practical Strategies: Best practices for navigating the enforcement process, including sharing case studies.",
      "Panel Discussion: Engage with a panel of distinguished experts in arbitration law who will share their experiences, insights, and predictions for the future of arbitration enforcement in Korea.",
      "Following the above sessions, attendees will have an opportunity to network with other participants to foster connections that could lead to collaborative opportunities in the future.",
      "We look forward to welcoming you to this essential seminar, where you will leave with practical insights and a better understanding of enforcement proceedings in Korea regarding arbitration awards.",
      "I Program",
      "10:30 - 10:40: Registration",
      "10:40 - 11:25: Seminar",
      "11:25 - 11:35: Q&A",
      "11:35 - 12:00: Networking",
      "I Speakers",
      "Changhyun Lee / BAE, KIM & LEE LLC / Partner",
      "Sangchul Kim / BAE, KIM & LEE LLC / Partner",
      "Bochan Kim / BAE, KIM & LEE LLC / Senior Foreign Attorney",
      "Introduction by Woojae Kim / BAE, KIM & LEE LLC / Partner",
      "I Contact Point",
      "​ Name: Woojae Kim, / Email: woojae.kim@bkl.co.kr",
      "Name: Hangil Lee / Email: hangil.lee@bkl.co.kr",
      "Name: Bochan Kim / Email: bochan.kim@bkl.co.kr",
    ],
  },
  "복제-tue-siac-ysiac": {
    contactInfo: ["kchung@cov.com"],
    registerHref: "https://go.cov.com/l/955523/2024-10-14/7813m",
    lines: [
      "Construction Arbitration Around the Globe",
      "I Overview",
      "Date: Tuesday, October 29, 2024",
      "Time: 11 am - 12 pm (Lunch will be served at Covington’s Seoul office)",
      "Format: Hybrid (Virtual and in-person watch party at Covington’s Seoul office)",
      "Language: English",
      "Venue: Covington & Burling LLP’s Seoul office (Address: 22nd floor, Meritz Tower, 382 Gangnam-daero, Gangnam-gu, Seoul 06232, Korea )",
      "Hosts:​​​",
      "I Event Description",
      "Many companies involved in construction projects face various types of challenges in different jurisdictions. This panel, consisting of construction arbitration experts from various jurisdictions, will discuss changing landscapes and offer perspectives from jurisdictions covering Asia, Middle East, Africa, Latin America and North America.",
      "I Program",
      "Panel discussion",
      "I Speakers",
      "Moderator / Speaker: Kyongwha Chung, Of Counsel, Seoul office",
      "Speakers:",
      "Nicole Duclos, Partner, New York office",
      "Erin Thomas, Partner, New York office",
      "Joseph Chedrawe, Partner, Dubai office",
      "William Lowery, Of Counsel, Washington D.C. office",
      "I Contact Point",
      "​ Name: Kyongwha Chung / Email: kchung@cov.com",
    ],
  },
  "tue-jipyong-simc": {
    contactInfo: ["smjun@jipyong.com"],
    registerHref: "https://www.jipyong.com/kr/board/jipyongNews_seminar.php?seq=6615",
    lines: [
      "Skills Workshop: Tools and Ingredients for a Successful Settlement",
      "I Overview",
      "Date: Tuesday, October 29, 2024",
      "Time: 1pm – 4pm (3 hours)",
      "Format: In-person",
      "Language: English",
      "Venue: KCAB Hearing Room 5",
      "Hosts:​​​",
      "I Event Description",
      "The Skills Workshop provides an opportunity to experience alternative dispute resolution in real-life scenarios. Participants can explore various tools and strategies for a successful negotiation and explore techniques to enhance communications, and build collaborative rapport, and master skills for managing complex legal disputes.",
      "I Program",
      "13:00-13:30 Ingredients for Settlement Strategy (Presentation and Negotiation Simulation by Jinhee Kim)",
      "13:30-14:20 Workshop #1: What Factors Work For and Against Settlement?",
      "14:20-14:30 Short Break",
      "14:30-14:45 Mediation as a Settlement Tool (Presentation by Wee Meng Chuan)",
      "14:45-15:45 Workshop #2: How Can Mediation Help Negotiations?",
      "15:45-16:00 Lessons Learned and Closing Remarks",
      "I Speakers",
      "Jinhee Kim/Jipyong LLC/Head of Global Dispute Resolution Practice",
      "Wee Meng Chuan/SIMC/Chief Executive Officer",
      "I Contact Point",
      "​ Name: Somin Jun / Email: smjun@jipyong.com",
    ],
  },
  "tue-hkiac-yulchon": {
    contactInfo: ["jpark@hkiac.org"],
    registerHref: "https://hkiac.glueup.com/event/arbitral-procedures-how-creative-have-we-been-and-can-we-go-further-122721/",
    lines: [
      "Arbitral Procedures – How creative have we been and can we go further?",
      "I Overview",
      "Date: Tuesday, October 29, 2024",
      "Time: 14:00 - 15:30 pm",
      "Format: In-person",
      "Language: English",
      "Venue: Yulchon, 39/F Parnas Tower, 521 Teheran-ro, Gangnam District, Seoul",
      "Expected number of participants: 50",
      "Hosts:​​​",
      "I Event Description",
      "On one end of the spectrum, some arbitrators and parties follow rigid and formalistic processes that resemble litigation. While these procedures ensure due process, they can limit the flexibility and adaptability that arbitration is meant to offer.",
      "The panel will invite speakers to share some of the more creative case management and procedural mechanisms they have seen or adopted to invite a thought-provoking discussion on whether they work, and test the limits of how far we can go in enhancing procedural efficiency without sacrificing fairness.",
      "I Contact Point",
      "​ Name: June Park / Email: jpark@hkiac.org",
    ],
  },
  "tue-dis": {
    contactInfo: ["jschaefer@kslaw.com"],
    registerHref: "https://dis-saf-seoul-2024.rsvpify.com/",
    lines: [
      "DIS@SAF: To be, or not to be sandwiched – The new DIS Supplementary Rules for Third-Party Notices",
      "I Overview",
      "Date: Tuesday, 29 October 2024",
      "Time: 15:00 - 17:00",
      "Format: In-person",
      "Language: English",
      "Venue: Peter & Kim, Trade Tower 38th Floor (#3805), 511 Yeongdong-daero, Gangnam-gu, Seoul 06164",
      "Hosts:​​​",
      "I Event Description",
      "Since 15 March 2024, the German Arbitration Institute (DIS) offers supplementary rules that allow for the filing of third-party notices in an arbitration. These new rules can help parties prevent being sandwiched in arbitration. We will discuss in what situations being sandwiched is a real risk and what in your experiences are ways to handle such situations. Can arbitration institutions remedy this perceived disadvantage of arbitration against litigation? Are the new DIS Supplementary Rules a model suitable for Asia?",
      "I Program",
      "3.00 pm Welcome & Sandwiches",
      "3.15 pm The DIS – The German Arbitration Institute",
      "3.25 pm The new DIS Supplementary Rules for Third Party Notices - A Short Introduction",
      "3.45 pm How Best to Prevent Sandwiching in Arbitration and How Can the DIS Supplementary Rules Help? – A Moderated Discussion with Views from Korea and Beyond",
      "4.45 pm Takeaway​",
      "I Speakers",
      "Helena Chen, ADR Chen & Chang, Taipei",
      "Mariel Dimsey, CMS, Hong Kong",
      "Mino Han, DIS Council Member, Seoul",
      "Joongi Kim, Yonsei University, Seoul",
      "Sue Hyun Lim, Kim & Chang, Seoul",
      "Lars Markert, DIS Advisory Board and DIS Council Member, Tokyo",
      "Le Net, LNT & Partners, Singapore",
      "Jan K. Schaefer, DIS Board Member, Frankfurt",
      "Chun-Kyung Paulus Suh, German Arbitration Institute (DIS), Berlin/Bonn",
      "I Contact Point",
      "​ Name: Jan K. Schaefer, DIS Board Member / Email: jschaefer@kslaw.com",
      "​​​​​",
    ],
  },
  "tue-shin-kim": {
    contactInfo: ["IDR_paralegal@shinkim.com"],
    registerHref: "https://www.shinkim.com/eng/seminar/invitation?id=279&secret=44bd237ac4cd66653addb37fcc0b1381ddaaaa37cdec0f7b110b730d66f26ff8",
    lines: [
      "Pitfalls to avoid when doing business in India",
      "I Overview",
      "Date: Tuesday, October 29, 2024",
      "Time: 16:30 – 18:00",
      "Format: In-person",
      "Language: English",
      "Venue: KCAB Hearing Room 5",
      "Hosts:​​​",
      "I Event Description",
      "Shin & Kim and Secretariat are pleased to invite you to a seminar on pitfalls to avoid when doing business in India. Gain valuable insights into cultural differences, regulations, and the importance of local partnerships while networking with industry experts and like-minded professionals.",
      "​",
      "Featured Speakers:",
      "Ramesh Iyer, Chairman of the Indian Chamber of Commerce in Korea (ICCK) and Country Head at TATA Consultancy Services(TCS), bringing over 15 years of experience in IT consulting and services globally",
      "Steven Lim, experienced arbitrator and barrister at 39 Essex Chambers with over 100 global appointments, specializing in commercial disputes across diverse jurisdictions, including India",
      "Chaitanya Arora of Secretariat, with over 25 years of experience in business valuations, damages quantification, mergers and acquisitions, and corporate finance, involving a variety of jurisdictions, such as India",
      "Duncan Watson KC, managing partner of the new Singapore office of Quinn Emanuel and one of Quinn Emanuel’s leaders of their Asian arbitration practice, specializing in international arbitration",
      "Youngwon Yoon, partner at Shin & Kim, possessing a high level of expertise in international arbitration, ISDS, WTO disputes, and trade remedies, including in relation to India",
      "I Program",
      "Speaking Session",
      "I Speakers",
      "Ramesh Iyer / Indian Chamber of Commerce in Korea (ICCK) / Chairman",
      "Steven Lim / 39 Essex Chambers / Arbitrator and Barrister",
      "Chaitanya Arora / Secretariat / Managing Director",
      "Duncan Watson KC / Quinn Emanuel / Managing Partner",
      "Youngwon Yoon / Shin & Kim LLC / Partner",
      "I Contact Point",
      "​ Name: : IDR_paralegal / Email: IDR_paralegal@shinkim.com",
    ],
  },
  "복제-thu-icc-1": {
    contactInfo: ["bami.yoo@leeko.com"],
    lines: [
      "The Lee & Ko Dinner",
      "I Overview",
      "Date: Tuesday, 29 October 2024",
      "Time: 19:00 - 21:00",
      "Format: In-person (Invitation-only)",
      "Language: English",
      "Venue: Mood Seoul, 2085-14, Olympic-daero, Seocho-gu, Seoul",
      "Hosts:​​​",
      "I Event Description",
      "The Lee & Ko International Team is delighted to continue the team’s tradition of hosting the Lee & Ko dinner party at this time of the year where fellow practitioners get together for an evening of music and networking.",
      "​",
      "This year, the Lee & Ko dinner will be held at Mood Seoul, overlooking the Han River, with a cocktail reception followed by a riverside dinner party as we celebrate the Seoul ADR Festival 2024.",
      "I Program",
      "7:00pm / Drinks Reception",
      "7:30pm / Riverside Dinner Party",
      "I Contact Point",
      "​ Name: Bami Yoo / Email: bami.yoo@leeko.com​​​",
    ],
  },
  "tue-yulchon": {
    contactInfo: ["s_jmyoo@yulchon.com"],
    lines: [
      "Yulchon Private Dinner & Yacht Cruise (invitation-only)",
      "I Overview",
      "Date: Tuesday, 29 October 2024",
      "Time: 7:00 p.m. – 10:00 p.m.",
      "Format: In-person",
      "Language: English",
      "Venue: Golden Blue Marina (1st Floor, 2085-14, Olympic-daero, Seocho-gu, Seoul)",
      "By Taxi: Please set navigation destination as [Sevit Island] or [Banpo Parking Lot 2]",
      "Host:",
      "I Event Description",
      "We are delighted to extend an exclusive invitation to esteemed arbitration practitioners for a private dinner and yacht cruise along the majestic Han River, held during the much-anticipated Seoul ADR Festival (SAF) week. This special event, hosted by Yulchon, is designed to provide an unparalleled opportunity to meet and engage with distinguished colleagues from the global arbitration community in an intimate and spectacular setting. This event provides a rare chance to exchange insights and strategies with peers, learn from the experiences of leaders in the field, and discuss potential collaborations in a less formal, more personable environment. As you network, the stunning views of the Han River will provide a refreshing and inspiring setting that encourages open, meaningful conversations. We are excited about the opportunity to host you and look forward to an evening of great food, insightful dialogue, and rewarding networking.",
      "I Contact Point",
      "​ Name: Jimin Yoo / Email: s_jmyoo@yulchon.com​​​",
      "I Registration Link",
      "By Invitation Only",
    ],
  },
  "복제-tue-yulchon": {
    lines: [
      "CMS Cocktail Reception",
      "I Overview",
      "Date: Tuesday, 29 October 2024",
      "Time: 8:00 p.m. ~",
      "Venue: Zest Seoul (B1 26 KR 55 Dosandaero 55-gil, Gangnam-gu, Seoul, South Korea)",
      "Host:",
      "I Event Description",
      "We are delighted to invite you to an exclusive CMS Cocktail Reception during the 2024 Seoul ADR Festival.",
      "The reception is scheduled for Tuesday, 29 October 2024, starting at 8:00 p.m. at Zest, a venue that has earned recognition among the Top 50 Bars in Asia.",
      "The CMS International Arbitration team very much hopes that the evening will provide an opportunity for us all to reconnect with our friends in Seoul and forge new connections over special cocktails and canapes at a memorable location.",
      "Looking forward to seeing you,",
    ],
  },
  "adr-conference-2024": {
    lines: [
      "The 13th Asia-Pacific ADR Conference",
      "ADR Reborn:",
      "Dynamics of Renewed Asian ADR Landscape",
      "30 October 2024 (Wed)",
      "09:00 am–18:00 pm KST",
      "Grand Intercontinental Seoul Parnas",
      "Orchid Room",
      "2F, 521, Teheran-ro,",
      "Gangnam-gu, Seoul, Korea",
      "The Conference will be broadcast live on KCAB INTERNATIONAL",
      "YouTube Channel (KCAB INTERNATIONAL - YouTube)",
      "Registration 08:00 - 09:00 (60 minutes)",
      "09:00 - 09:15 am",
      "Welcome",
      "Remarks",
      "Seung Wha Chang Chairman, KCAB INTERNATIONAL",
      "Congratulatory",
      "Anna Joubin-Bret Secretary, UNCITRAL",
      "Opening",
      "Sung Jae Park Minister, Ministry of Justice Korea",
      "09:15 - 09:50 am",
      "\"Recent Developments in International Arbitration\"",
      "Keynote",
      "Speech",
      "Gary Born Chair of the International Arbitration Practice Group, Wilmer Cutler Pickering Hale and Dorr",
      "Coffee Break 09:50 - 10:00 (10 minutes)",
      "Gloria Lim CEO, SIAC",
      "Session 1",
      "10:00 - 12:00 (120 minutes)",
      "Topic",
      "“Developing User-Friendly Asian Model ADR Services\"",
      "An assessment of the current status of Asian ADR/arbitration market",
      "Diagnosis/ Reality Check: Asia Arbitration Assessment",
      "Finding the Asian Model for properly restructuring the linkage between arbitration and other ADR (including mediation) services",
      "Co-Moderators",
      "Christopher Lau SC Independent Arbitrator, 3VB",
      "Speakers",
      "Andrew Sek-Hwan Hong Vice President, Hyundai Heavy Industries",
      "Joongi Kim Professor of Law, Yonsei University",
      "Joanne Lau Secretary-General, HKIAC",
      "Jae Sung Lee Senior Legal Officer, UNCITRAL",
      "Helen Shi Vice President, ICC Court / Partner, Fangda Partners",
      "Pui-Ki Emmanuelle Ta Independent Arbitrator",
      "Hiroyuki Tezuka Partner, Nishimura & Asahi",
      "Lunch Break 12:00 - 13:30 (90 minutes)",
      "Session 2",
      "13:30 - 14:50 (80 minutes)",
      "\"Emerging and Fast-Growing Intellectual Property and Technology-Related Dispute Areas in Asia\"",
      "Conducting a comprehensive analysis of recent developments and challenges within the intersection of IP and technology related dispute in Asia.",
      "Kevin Kap-You Kim Founding Partner, Peter & Kim",
      "Nicolas Wiegand Partner, CMS",
      "John Choong Partner, Freshfields",
      "Nils Eliasson Partner, King & Spalding",
      "Jinhee Kim Partner, Jipyong",
      "Yeji Kim Legal Counsel, Oracle",
      "Robert Wachter Partner, Shin & Kim",
      "Coffee Break 14:50 - 15:00 (10 minutes)",
      "Session 3",
      "15:00 - 16:20 (80 minutes)",
      "\"ADRs in Asia for Construction and Energy Industry\"",
      "Review the successes and challenges of ADR in the construction and energy sectors in Asia, and discuss how we can improve practices going forward.",
      "Byung-Woo Im Partner, Kim & Chang",
      "Abby Cohen Smutny Partner, White & Case",
      "Yun Jae Baek Partner, Yulchon",
      "Cavinder Bull SC CEO, Drew & Napier",
      "David Delman Senior Executive Vice President, Samsung Engineering",
      "Jonathan Humphrey Partner/Chartered Accountant, HKA",
      "Steve Kim Secretary-General, KCAB INTERNATIONAL",
      "Coffee Break 16:20 - 16:30 (10 minutes)",
      "Session 4",
      "16:30 - 17:50 (80 minutes)",
      "\"ISDS – An Asian Model?\"",
      "Reflect on the ongoing reform of ISDS and explore certain features, transparency, and TPF, in the Asian context.",
      "Hi-Taek Shin Independent Arbitrator, Twenty Essex",
      "Aurelia Antonietti Senior Legal Adviser, ICSID",
      "Arne Fuchs Partner, Ashurst",
      "Yoshimi Ohara Partner, Nagashima Ohno & Tsunematsu",
      "Junyeul (Alex) Yang Public Prosecutor, Ministry of Justice Korea",
      "David Kim Partner, Baker McKenzie KL Partners",
    ],
  },
  "wed-iba": {
    contactInfo: ["Joey.Feng@int-bar.org"],
    registerHref: "https://www.ibanet.org/conference-details/CONF2582",
    lines: [
      "A deep dive into renewable energy-disputes in the Asia Pacific region and the IBA's revised Guidelines on Conflicts of Interest",
      "I Overview",
      "Date: Wednesday, October 30, 2024",
      "Time: 16:00 – 18:30",
      "Format: In-person",
      "Language: English",
      "Venue: Hearing room 5",
      "Hosts:​​​",
      "I Event Description",
      "N/A",
      "I Program",
      "Opening remarks:",
      "Speaker: Mr. Lawrence Teh (Dentons, Singapore)",
      "Session 1 (16:00-17:00): A discussion on the rise of renewable energy-related disputes in the Asia Pacific region",
      "Moderator: Ms. Kyongwha Chung (Covington & Burling, USA)",
      "Speaker: Ms. Joyce Chen (Lee & Li, Taiwan)",
      "Speaker: Mr. Sang Hoon Han (Lee & Ko, South Korea)",
      "Speaker: Ms. Sophia Kim (Korea Electric Power Corporation, South Korea)",
      "Speaker: Mr. Joaquin Terceño (Eversheds, England)",
      "Speaker: Mr. Jae Hyong Woo (Yulchon, South Korea)",
      "Networking break: 17:00-17:30",
      "Session 2 (17:30 -18:30): A discussion on the IBA’s revised Guidelines on Conflicts of Interest in International Arbitration",
      "Moderator: Ms. Huawei Sun (Zhong Lun Law Firm, China)",
      "Speaker: Ms. Ara Cho (Peter & Kim, South Korea)",
      "Speaker: Professor Joongi Kim (Yonsei Law School, South Korea)",
      "Speaker: Mr. Harold Noh (Kim & Chang, South Korea)",
      "Speaker: Mr. Young Suk Park (Shin & Kim, South Korea)",
      "Closing remarks:",
      "I Contact Point",
      "​ Name: Joey Feng / Email: Joey.Feng@int-bar.org",
    ],
  },
  "wed-peter-kim": {
    contactInfo: ["ContactSE@peterandkim.com"],
    registerHref: "https://forms.gle/nXbEroFefrqNwok29",
    lines: [
      "Peter & Kim K-Arts Concert",
      "I Overview",
      "Date: Wednesday, 30 October 2024",
      "Time: 19:00 - 22:00",
      "Format: In-person",
      "Language: English",
      "Venue: Lee Kang Sook Hall, 4F, Korea National University of Arts, Seocho-dong Campus",
      "2374 Nambusunhwan-ro, Seocho-gu, Seoul",
      "Hosts:​​​",
      "I Contact Point",
      "​ Name: : Bokyeong Park / Email: ContactSE@peterandkim.com",
    ],
  },
  "복제-tue-shin-kim": {
    contactInfo: ["kchung@cov.com"],
    registerHref: "https://forms.gle/jvKLgQsWQUVnKfVV7",
    lines: [
      "Past, Present and Future of Arbitration in Asia: Diversity and Inclusion",
      "I Overview",
      "Date: Wednesday, October 30, 2024",
      "Time: 19:00 - 21:00",
      "Format: In-person",
      "Language: English",
      "Venue: Yulchon’s office",
      "Host:​​​",
      "​",
      "Supporting Organizations:",
      "I Event Description",
      "This panel will discuss “diversity and inclusion” issues in Asia, covering Korea, Singapore, Japan and Hong Kong. “Diversity and inclusion\" issues and challenges faced by Asian societies are different from those faced by the western world.",
      "We will have a roundtable discussion on the past, present and future of Asian arbitration community dealing with \"diversity and inclusion\" challenges both within Asia and broader global community.",
      "I Program",
      "Panel discussion",
      "I Speakers",
      "Welcome Remarks: Myung-Ahn Kim / Yoon & Yang LLC / Head of International Dispute Resolution",
      "Moderator: Kyongwha Chung / Covington & Burling LLP / Of Counsel",
      "Speakers:",
      "Joanne Lau / HKIAC / Secretary-General",
      "Wendy Lin / WongPartnership / Partner",
      "Lars Markert / Nishimura & Asahi / Partner",
      "Moses Sye / OW Ocean Winds / Head of Legal",
      "Hangil Lee / Bae, Kim & Lee LLC / Partner",
      "Young Shin Um / Senior Deputy Director / International Dispute Settlement Division / Ministry of Justice",
      "Closing Remarks:",
      "Sophie Jeonghye Ahn / Yulchon / Co-chair of International Dispute Resolution Team",
      "I Contact Point",
      "​ Name: Kyongwha Chung / Email: kchung@cov.com",
    ],
  },
  "thu-kim-chang-scma": {
    contactInfo: ["minju.kim@kimchang.com", "arbitration_news@kimchang.com"],
    registerHref: "https://forms.office.com/pages/responsepage.aspx?id=Qnc4CY_UoU-QjAzAupN1z9r0v8L4wOpPuo_Gk7BW8cdURFFSVUZaWjZYWU00VDlISFU4RjVUUDE1MSQlQCN0PWcu&route=shorturl",
    lines: [
      "Challenging Arbitration Awards: A Review of Recent Singaporean, Korean and Vietnamese Arbitration Decisions",
      "I Overview",
      "Date: Thursday, 31 October 2024",
      "Time: 9:30 a.m. – 12 p.m. (noon)",
      "Format: In-person",
      "Language: English",
      "Venue: KCAB Hearing Room 5",
      "Hosts:​​​",
      "I Event Description",
      "Jointly organised by Kim & Chang together with the Singapore Chamber of Maritime Arbitration, the SCMA Seoul Conference 2024 is focused on exploring topics relevant to international maritime & international trade arbitration. SCMA Seoul Conference 2024 will feature speakers from Kim & Chang along with SCMA corporate member firms. The SCMA Seoul Conference 2024 offers a unique platform for networking, knowledge exchange, and shaping the future of maritime arbitration.",
      "I Program",
      "9:30 am Registration Networking with Light Breakfast, Coffee & Tea",
      "9:50 am Welcome by SCMA",
      "9:55 am Opening Remarks by Chul-Won Lee, Kim & Chang",
      "10:00 am Keynote Address by Captain In-Hyun Kim, President of Korea Maritime Arbitrators Forum and Emeritus Professor of Korea University School of Law",
      "10:10 am Challenging Singaporean Awards by Mr Probin Dass, DennisMathiew",
      "10:30 am Challenging Korean Awards by Mr Daehee Lee, Kim & Chang",
      "10:50 am Mid-Morning Coffee/Tea Break",
      "11:10 am A Practical Guide on using the SCMA Rules",
      "11:30 am Challenging Vietnamese Awards by Ms Dang Vu Minh Ha, Dzungsrt & Associates",
      "11:50 am Panel Q&A Session",
      "12:00 pm End of Conference",
      "I Contact Point",
      "For Registration:",
      "Email: minju.kim@kimchang.com",
      "tricia@scma.org.sg",
      "​",
      "General Inquiries:",
      "Email: arbitration_news@kimchang.com",
      "​​​​​",
    ],
  },
  "복제-fri-limnexus-svamc-steve": {
    contactInfo: ["vera.he@iccwbo.org"],
    registerHref: "https://events.iccwbo.org/event/?id=2024_DRS_North_Asia_ICC_Potluck_Gathering_The_New_Cross-Cultural_Playbook_for_Global_Arbitration3807343148",
    lines: [
      "ICC Potluck Gathering: The New Cross-Cultural Playbook for Global Arbitration",
      "I Overview",
      "Date: Thursday, 31 October 2024",
      "Time: 11:30 - 13:30",
      "Format: In-person",
      "Language: English",
      "Venue: Yeoyul Café, 39th floor of Yulchon Office, Parnas Tower, 521 Teheran-ro, Gangnam-gu, Seoul 06164, Korea",
      "Hosts:​​​",
      "I Event Description",
      "The International Chamber of Commerce (ICC), Jus Connect, and McCann Truth Central conducted an intriguing study titled The Truth About Cross-Cultural B2B Relationships. The study’s findings are provided to help businesses and law firms create more successful communication plans for cross-border trade. One of its analyses showed a strong need to remap the world based on cultural differences and similarities rather than geographical positioning.",
      "The event theme this year based on this research report and focus on “The New Cross-Cultural Playbook for Global Arbitration”, where arbitration professionals are invited to share their cross-cultural arbitration experiences and bring the business and legal culture of Asia to global community's awareness.",
      "We welcome arbitration practitioners and business professionals to attend this event and keep up-to-date with the latest practice and developments in international arbitration while having a free and networking lunch together.",
      "I Program",
      "11.30-12.00 Registration and free lunch",
      "12.00-12.20 Keynote Speech",
      "Donna Huang, Regional Director, ICC Arbitration and ADR for North Asia, ICC Dispute Resolution Services",
      "12.20-13.20 Panel Discussion",
      "Bami Yoo, Partner, Lee & Ko, Seoul",
      "Eun Nyung (Ian) Lee, Partner, Yulchon, Seoul",
      "Eun Young Park, Senior Partner, Lee &Ko, Seoul",
      "Pui-Ki Emmanuelle Ta, Independent Arbitration Practitioner, Former ICC (Asia Office) Counsel and Secretary General of eBRAM, Hong Kong",
      "​​​",
      "Moderator",
      "Vera He, Deputy Director, ICC Arbitration and ADR for North Asia, ICC Dispute Resolution Services",
      "13.20-13.30 Q&A",
      "I Speakers",
      "Bami Yoo, Partner, Lee & Ko",
      "I Contact Point",
      "​ Name: Vera He / Email: vera.he@iccwbo.org ​​​",
    ],
  },
  "복제-thu-icc": {
    registerHref: "https://www.lcia.org/events/2024-insights-from-the-institution-interactive-panel-discussio-320.aspx",
    lines: [
      "Insights from the Institution - interactive panel discussion and a conversation with the LCIA Director General",
      "I Overview",
      "Date: Thursday, 31 October 2024",
      "Time: 15:00 - 18:00",
      "Format: In-person",
      "Language: English",
      "Hosts:​​​",
      "I Event Description",
      "Engage directly with thought leaders during an interactive panel discussion and an intimate fireside chat with LCIA Director General, where they will share their perspectives on the evolving challenges and opportunities in arbitration and the latest news from the LCIA. Following the discussions, there will be an opportunity to meet and mingle with fellow delegates and panelists to exchange ideas and foster relationships.",
    ],
  },
  "thu-ihcf-kocia": {
    contactInfo: ["hyesung.kim@kimchang.com"],
    lines: [
      "Enforcement and Setting Aside of Arbitral Awards",
      "I Overview",
      "Date: Thursday, 31 October 2024",
      "Time: 16:30 - 18:00",
      "Format: In-person",
      "Language: Korean",
      "Venue: Hearing Room 5, KCAB",
      "Hosts:​​​",
      "I Event Description",
      "With the accumulation of international arbitration awards among the parties to international transactions, there is a growing need to understand the requirements for recognition and enforcement of arbitration awards in each country, or the cases where the award may be set aside.",
      "​",
      "In particular, we will review the status of the enforcement of arbitral awards in countries where Korean companies frequently trade, and discuss future considerations for Korean companies to adopt arbitration agreements in international transactions based on recent cases of recognition or cancellation of international arbitral awards.",
      "I Program",
      "Introduction of basic principles for the enforcement and setting aside of arbitral awards",
      "Panel discussion regarding recent cases and experiences in various jurisdiction",
      "I Speakers",
      "Welcome Remark:",
      "Dang Huh (Chair of Arbitration Committee, In-House Counsel Forum)",
      "Moderator:",
      "Kyongwha Chung (Of Counsel, Covington & Burling LLP)",
      "Speakers:",
      "Scott Sung Hwan Kim (Chair of Labor & Employment Committee, In-House Counsel Forum)",
      "Dana Kim (Global Co-Chair of Korea Group, Herbert Smith Freehills",
      "Hye Sung Kim (Attorney, Kim & Chang)",
      "Closing Remark:",
      "Sae Youn Kim (President, Korean Council of International Arbitration)",
      "I Contact Point",
      "​ Name: Hye Sung Kim / Email: hyesung.kim@kimchang.com​​​",
    ],
  },
  "thu-acica-peter-kim": {
    contactInfo: ["ksanghera@acica.org.au", "dtomkinson@peterandkim.com"],
    registerHref: "https://acica.org.au/events-2/#!event/2024/10/31/agricultural-trade-matters-8220-beefing-up-8221-the-australia-korea-commercial-relationship",
    lines: [
      "Agricultural Trade Matters: “Beefing Up” the",
      "Australia-Korea Commercial Relationship",
      "I Overview",
      "Date: Thursday, 31 October 2024",
      "Time: 17:00 - 18:30 followed by a drinks reception",
      "Format: In-person",
      "Language: English",
      "Venue: Peter & Kim, #3805 Trade Tower, 511 Yeongdong-daero, Gangnam-gu, Seoul 06164",
      "Hosts:​​​",
      "I Event Description",
      "Australia and Korea have unique, deep and long-established economic ties. Supportive frameworks, such as the Korean-Australian Free Trade Agreement (KAFTA), have worked to promote, liberalise and protect trade between the two countries significantly. Agricultural trade – think: food, wine and textiles - forms an important part of Australia’s commercial relationship with Korea, Australia’s fourth largest trading partner. Importantly and thankfully, cross-border disputes between Korea and Australia, generally and in agriculture specifically, are few and far between. Why is this? How can we maintain this? How can the agricultural relationship serve as an example for other sectors and trade relationships? It will also be an enjoyable occasion to show-case Australian agriculture, sharing some of the best of Australian food and wine.",
      "I Program",
      "Panel Discussion",
      "I Speakers",
      "To follow",
      "I Contact Point",
      "​ Name: Kiran Sanghera (ACICA) / Email: ksanghera@acica.org.au",
      "​ Deborah Tomkinson (Peter & Kim) / Email: dtomkinson@peterandkim.com",
    ],
  },
  "tue-jipyong": {
    contactInfo: ["yilee@jipyong.com"],
    registerHref: "https://www.jipyong.com/kr/board/jipyongNews_seminar.php?seq=6613",
    lines: [
      "Fireside Chat with Clients",
      "I Overview",
      "Date: Thursday, 31 October 2024",
      "Time: 18:00 – 21:00",
      "Format: In-person",
      "Language: English",
      "Venue: 26F, Grand Central A, 14 Sejong-daero, Jung-gu, Seoul",
      "Hosts:​​​",
      "I Event Description",
      "Jipyong, Mori Hamada & Matsumoto, MDD, and Oppenheim invite you to a special evening with in-house counsel at Korea's most prominent companies. This event will be a rare and unique opportunity for practitioners and professionals to converse about their experiences and ideas in a cordial setting. The highlight of the event will be a panel discussion among distinguished in-house counsel, followed by a networking dinner showcasing a panoramic nighttime view of downtown Seoul and Namdaemun. Event is by registration only.",
      "I Program",
      "I Welcome remarks by",
      "Jipyong: Jinhee Kim (Head of Global Dispute Resolution Practice)",
      "Mori Hamada & Matsumoto: Daniel Allen (Partner, Dispute Resolution)",
      "MDD: Jerome McDonagh (Director)",
      "Oppenheim: Tamás Éless (Partner, Dispute Resolution)",
      "I Contact Point",
      "​ Name: Lee, Yong Ik / Email: yilee@jipyong.com",
      "​​​​​",
    ],
  },
  "tue-yiag": {
    registerHref: "https://www.lcia.org/events/yiag-korea-321.aspx",
    lines: [
      "YIAG Meet & Mingle in Korea",
      "I Overview",
      "Date: Thursday 31 October 2024",
      "Time: 18:00 - 21:30",
      "Format: In-person",
      "Language: English",
      "Hosts:​​​",
      "I Event Description",
      "In this informal setting, attendees will have the opportunity to engage in an 'ask anything' Q&A session with LCIA Director General, Professor Dr Jacomijn (Jackie) van Haersolte-van Hof; LCIA Court Member Byung-Chol (BC) Yoon (Kim & Chang) and Professor Hi-Taek Shin (Twenty Essex). This is a fantastic chance for young international arbitration practitioners to glean insights and experiences from esteemed mentors.",
    ],
  },
  "fri-limnexus-svamc-steve": {
    contactInfo: ["elizabeth.chan@sw-hk.com", "Grant.Kim@limnexus.com", "justin.kim@sw-hk.com"],
    registerHref: "https://docs.google.com/forms/d/e/1FAIpQLSdJxbUpqogF1wy4kukcONN0eLn15d5tiFFuUFneAs9uf-aeAQ/viewform",
    lines: [
      "Navigating the Use of Artificial Intelligence in Arbitration:",
      "Practical Scenarios, Ethical Issues, and Best Practices",
      "I Overview",
      "Date: Friday, 1 November 2024",
      "Time: 09:00 - 10:30 (light continental breakfast)",
      "Format: In-person only",
      "Language: English",
      "Venue: KCAB, 18F Trade Tower, 511 Yeongdong-daero,Gangnam-gu, Seoul 06164, Korea",
      "Hosts:​​​",
      "I Event Description",
      "This panel will delve into critical, practical questions surrounding the integration of generative artificial intelligence (AI) in international arbitration, guided by the newly developed Silicon Valley Arbitration and Mediation Center’s (SVAMC) Guidelines on Using Artificial Intelligence in Arbitration (Guidelines).",
      "These Guidelines incorporate extensive feedback from the international arbitration community. The panel will address a range of pressing and specific concerns practitioners increasingly encounter as AI becomes more intertwined with the practice of international arbitration, including:",
      "​​",
      "AI in Drafting: Is it permissible to use AI tools for drafting awards, submissions, and expert reports? Should the use of such tools be disclosed to all parties involved?",
      "Undisclosed AI Use: How should instances of undisclosed AI use be managed within arbitration proceedings?",
      "Confidentiality Issues: What measures are necessary to safeguard confidentiality when employing AI in arbitration?",
      "AI-Generated Evidence: How can practitioners protect against AI-manipulated evidence and address the risks of AI “hallucinations” (inaccurate or fabricated information)?",
      "Understanding Generative AI: What are the underlying mechanisms of generative AI, and what inherent risks do they pose to the integrity of arbitration?",
      "The panel will feature SVAMC members who contributed to the drafting of these guidelines or have significant experience with AI and arbitration. It aims to equip arbitration professionals with specific knowledge and strategies needed to effectively harness AI, enhancing efficiency while maintaining the fairness and integrity of arbitration processes.",
      "I Program",
      "Introduction to the SVAMC Guidelines on Using AI in Arbitration",
      "Introduction to Generative AI",
      "Discussion of hypothetical scenarios involving the use of AI in arbitration settings",
      "Conclusion",
      "I Speakers",
      "Elizabeth Chan, Consultant, Stevenson, Wong & Co., Hong Kong",
      "Grant Kim, Partner, LimNexus LLP, San Francisco",
      "David MacArthur, Yulchon, Co-head of International Dispute Resolution, Seoul",
      "Sunyoung Kim, Partner, Baker McKenzie & KL Partners, Seoul",
      "Lexi Takamatsu, Mori Hamada & Matsumoto, Foreign Law Counsel, Tokyo",
      "I Contact Point",
      "​ Name: Elizabeth Chan / Email: elizabeth.chan@sw-hk.com​",
      "Name: Grant L. Kim / Email: Grant.Kim@limnexus.com​",
      "Name: Justin Kim / Email: justin.kim@sw-hk.com",
      "​​​​​",
    ],
  },
  "fri-litig": {
    contactInfo: ["info@litigep.com", "taehun.lee@litigep.com"],
    lines: [
      "TPF(Third-Party Funding) Utilization for Cross-border Disputes (Lunch Seminar)",
      "I Overview",
      "Date: Friday, 1 November 2024",
      "Time: 10:00 - 14:00 (inclusive networking lunch)",
      "Format: In-person",
      "Language: Korean + English",
      "Venue: 3F (Salon 6), JW Marriott Hotel Seoul",
      "Registration : info@litigep.com (invitation-only)",
      "Hosts:​​​",
      "I Event Description",
      "In the second half of 2024, the South Korean economy is facing various challenges. The uncertainty of the global economy, changes in the trade environment, and domestic and international political factors are collectively bringing our economy to a new turning point. In particular, rising prices, interest rate fluctuations, and the reorganization of global supply chains are significantly impacting the economic activities of businesses and individuals. Meanwhile, companies continue to experience financial difficulties due to various disputes in their overseas operations, necessitating strategic responses.",
      "In this context, LITIG Equity Partners invites you to discuss the strategic responses to cross-border disputes for globally expanding companies, based on the real experiences of domestic and international experts, and the successful utilization strategies of TPF. We look forward to the interest and participation of corporate clients.",
      "I Program",
      "Please refer to seminar flyer​",
      "I Speakers",
      "I Contact Point",
      "​ Name: TaeHun Lee / Email: taehun.lee@litigep.com",
      "​​​​​",
      "Download Flyer (KOR)",
      "Download Flyer (ENG)",
    ],
  },
  "fri-watsonfarley-williams": {
    contactInfo: ["ryang@wfw.com"],
    registerHref: "https://comms.wfw.com/v/coesoaxc",
    lines: [
      "Public International Law: Emerging and Future Disputes",
      "I Overview",
      "Date: Friday, 1 November 2024",
      "Time: 11:30 - 14:00",
      "Format: In-person",
      "Language: English",
      "Venue: Lotte Hotels & Resorts 36th Floor, Belle-Vue Suite Eulji-ro 30, Jung-gu, Seoul, Korea (04533)",
      "Hosts:​​​",
      "I Event Description",
      "In recent years, there has been a growing focus on dispute settlement mechanisms available under international law. Both States and private actors are increasingly recognising the potential of these mechanisms to resolve their differences and enforce rights across various domains, including in regard to investment issues, climate change measures, international conflicts, and deep seabed mining. Understanding how to access and utilise these international dispute settlement mechanisms is crucial for firms operating across borders and for States in their international engagements.",
      "​",
      "Join us for an engaging seminar that delves into the key issues and latest developments in dispute settlement mechanisms under international law, with a particular emphasis on dispute settlement in the context of deep seabed mining in international waters and recent cases of significance in the field of public international law, and the broader lessons they offer for international dispute resolution.",
      "Attendees at our seminar can look forward to learning about:",
      "The International Seabed Authority (ISA), its role under the United Nations Convention on the Law of the Sea (UNCLOS) and its governance of deep seabed mining in the parts of the seabed that are outside of national jurisdiction (known as the Area). The Area is rich in several key mineral resources that could be critical to realising the energy transition and net zero goals. As such, it presents significant opportunities for private contractors and States.",
      "The latest developments at the ISA and its negotiations of regulations governing exploitation of mineral resources in the Area, which it is aiming to adopt in 2025. Once adopted, these regulations are poised to set a key precedent in international law, incorporating and setting best environmental practices for seabed mineral activities.",
      "Korea’s role at the forefront of this work, including as one of the few ‘pioneering investors’ in deep seabed mining in the Area under UNCLOS, as a holder of contracts for undertaking exploration activities in the Area, and through its active engagement with negotiations of regulations governing commercial exploitation of resources in the Area.",
      "The unique dispute settlement mechanism established under UNCLOS for deep seabed mining in the Area. This mechanism includes the ability of private contractors to bring claims directly against States and the ISA at the international level, providing much needed certainty for investors through an avenue to enforce their rights.",
      "Recent investor-State arbitration decisions, which have wider implications for international disputes.",
      "These insights into the international legal regime governing deep seabed mining will be contextualised within broader trends in international dispute settlement. They will also be accompanied by an update on key public international law cases over the last 12 months. This will ensure that attendees can gain a broader perspective of the international dispute settlement landscape, and relevance of these topics to their work.",
      "The seminar will also provide attendees with the opportunity to engage with the leading professionals in these areas, ask questions, exchange ideas, and gain a deeper understanding of the complex interplay between international law and emerging global disputes.",
      "I Program",
      "Lunch & Learn",
      "11:30 - 12:00: Networking and lunch",
      "12:00 - 13:00: Seminar",
      "13:00 - 13:30: Q&A",
      "13:30 - 14:00: Coffee and networking\"",
      "I Speakers",
      "Nathan Eastwood, Dispute Resolution Partner, Sydney",
      "Philip Kim, Dispute Resolution Partner, Seoul",
      "Haeran Chung, Dispute Resolution Senior Associate, Sydney",
      "I Contact Point",
      "​ Name: Rina Yang / Email: ryang@wfw.com",
      "​​​​​",
    ],
  },
  "fir-peterkim": {
    contactInfo: ["ContactSE@peterandkim.com"],
    registerHref: "https://forms.gle/nS6ydhP9vzSxCkzV9",
    lines: [
      "Witness Conferencing: The Idea, Methods and Practice",
      "I Overview",
      "Date: Friday, 1 November 2024",
      "Time: 14:00 - 16:00",
      "Format: In-person only",
      "Language: English",
      "Venue: KCAB Hearing Room 5, Trade Tower 18th floor",
      "Hosts:​​​",
      "I Event Description",
      "Co-hosts, Peter & Kim, Clifford Chance and WilmerHale are pleased to invite you to join us for this interactive exploration of the evolution of witness conferencing in international arbitration, being held during Seoul ADR Festival.",
      "​",
      "Since Dr Wolfgang Peter advanced the concept of witness conferencing in international arbitration more than 20 years ago, we have seen the practice flourish, with mixed application and outcomes. In a lively discussion moderated by Kevin Kim (Peter & Kim), and drawing on the extensive experience our expert speakers, Dr Peter (Peter & Kim), Jason Fry KC (Clifford Chance) and Matteo Angelini (WilmerHale) this session will consider how witness conferencing came to be, its development and use over time, and question whether it has met its potential, or now requires a fresh approach.",
      "With limited places available, please register using the link below to secure your spot. We look forward to welcoming you!",
      "I Speakers",
      "Kevin Kim / Peter & Kim / Founding Partner",
      "Dr. Wolfgang Peter / Peter & Kim / Founding Partner",
      "Jason Fry KC / Clifford Chance / Partner (Head of International Arbitration)",
      "Matteo Angelini / WilmerHale / Counsel",
      "I Contact Point",
      "​ Name: Bokyeong Park / Email: ContactSE@peterandkim.com​",
      "​​​",
    ],
  },
  "fri-dentonslee": {
    contactInfo: ["kurt.gerstner@dentons.com"],
    registerHref: "https://forms.office.com/r/D9HieBDW1z",
    lines: [
      "Expert Evidence Can Make or Break Your Case – Proven Strategies to Win!",
      "I Overview",
      "Date: Friday, 1 November 2024",
      "Time: 16:00 - 18:00",
      "Format: In-person",
      "Language: English",
      "Venue: Hearing room no. 1",
      "Hosts:​​​",
      "I Event Description",
      "Expert testimony is crucial in helping tribunals understand complicated facts, technology, and science in a dispute. Finding, selecting and optimally utilizing experts, and effectively challenging the testimony and opinions of your opponent’s experts, can mean the difference between success and failure in your arbitration. This panel of experienced disputes lawyers and an expert witness will help you develop winning expert strategies in arbitration and litigation.",
      "Topics to be discussed will include identifying issues requiring expert evidence; determining the types of experts needed; selecting non-testifying experts to assist with your understanding of technical issues, case development and strategies vs. finding and utilizing independent testifying experts; strategies and preparation for undermining opposing experts’ opinions and testimony including through cross-examination; use of joint expert statements and witness conferencing; managing time and cost expectations in the use of experts; the importance of the tribunal regulating issues on which expert evidence may be adduced; strategies for approaches to tribunal-appointed experts; due process issues in the hearing and standards for evaluation of expert evidence.",
      "I Program",
      "This panel discussion is focused on providing strategies and tips to make more effective use of your experts and better challenges to your opponents’ experts in international arbitration. Arbitration practitioners, in-house counsel and arbitrators all will find the program interesting and the information useful.",
      "Registration/Networking – 3:30-4:00 pm",
      "Program – 4:00 to 5:30 pm",
      "Reception – 5:30 to 6:00 pm",
      "I Speakers",
      "Lawrence Teh, Dentons Rodyk, Senior Partner and Global Co-Head of Dentons’ International Arbitration Group.",
      "Kurt Gerstner, Dentons Lee, Senior Attorney",
      "John Kim, Dentons Lee, Senior Attorney",
      "Michele Park Sonen, SIAC, Director & Head, North East Asia",
      "Braden Billiet, FTI Consulting, Senior Managing Director",
      "I Contact Point",
      "​ Name: Kurt Gerstner / Email: kurt.gerstner@dentons.com",
      "​​​​​",
    ],
  },
};

export const saf2024EventDetails: Record<string, Saf2024EventDetail> = Object.fromEntries(
  Object.entries(saf2024RawDetails).map(([slug, detail]) => [
    slug,
    {
      contactInfo: detail.contactInfo,
      registerHref: detail.registerHref,
      sections: buildSections(detail.lines),
    },
  ]),
);
